import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>トップページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>ここ何書くか悩む、/usersとか持ってきてもいいかも</div>
      <div>現状サイドメニューの導線、現状社員一覧だけありまする</div>
    </>
  );
}
